CONFIG = {
	'name': 'LAC',
	'token': '5047508356:AAHFJKcsr2GPbydVHjnXn8DiLEBVlluJqd0'
}
TEAM = {
	'LAC':'Los-Angeles Clippers',
	'LAL':'Los-Angeles Lakers',
	'GSW':'Golden State Warriors',
	'PHO':'Phoenix Suns',
	'SAC':'Sacramento Kings',
	'DAL':'Dallas Mavericks',
	'HOU':'Houston Rockets',
	'MEM':'Memphis Grizzlies',
	'NOP':'New Orleans Pelicans',
	'SAS':'San Antonio Spurs',
	'POR':'Portland Trail Blazers',
	'MIN':'Minnesota Timberwolves',
	'OKC':'Oklahoma City Thunder',
	'DEN':'Denver Nuggets',
	'UTA':'Utah Jazz',
	'CHI':'Chicago Bulls',
	'CLE':'Cleveland Cavaliers',
	'DET':'Detroit Pistons',
	'IND':'Indiana Pacers',
	'MIL':'Milwaukee Bucks',
	'ATL':'Atlanta Hawks',
	'CHO':'Charlotte Hornets',
	'MIA':'Miami Heat',
	'ORL':'Orlando Magic',
	'WAS':'Washington Wizards',
	'BOS':'Boston Celtics',
	'NYK':'New York Knicks',
	'BRK':'Brooklyn Nets',
	'PHI':'Philadelphia 76ers',
	'TOR':'Toronto Raptors'
}